export const products = [
  {
    id: 1,
    imgURL: "/products/black-galaxy.jpeg",
    name: "Black Galaxy",
    category: "Granite",
    bestFor: "Kitchen countertops, luxury kitchens",
  },
  { 
    id: 2,
    imgURL: "/products/black-white-granite.jpeg",
    name: "Black & White",
    category: "Granite",
    bestFor: "Modern floors, wall cladding",
  },
  {
    id: 3,
    imgURL: "/products/gold-carara.jpeg",
    name: "Gold Carrara",
    category: "Marble",
    bestFor: "Living rooms, feature walls",
  },
  {
    id: 4,
    imgURL: "/products/gold-galaxy.jpeg",
    name: "Gold Galaxy",
    category: "Granite",
    bestFor: "High-end kitchens, statement countertops",
  },
  { 
    id: 5,
    imgURL: "/products/magnifico.jpeg",
    name: "Magnifico",
    category: "Marble",
    bestFor: "Luxury interiors, hotel-style finishes",
  },
  { 
    id: 6,
    imgURL: "/products/pure-white.jpeg",
    name: "Pure White",
    category: "Marble",
    bestFor: "Minimalist interiors, bathrooms",
  },
  {
    id: 7,
    imgURL: "/products/red-aswan-granite.jpeg",
    name: "Red Aswan",
    category: "Granite",
    bestFor: "Outdoor spaces, decorative accents",
  },
  {
    id: 8,
    imgURL: "/products/silver-galaxy.jpeg",
    name: "Silver Galaxy",
    category: "Granite",
    bestFor: "Kitchen tops, office interiors",
  },
  {
    id: 9,
    imgURL: "/products/steel-grey-granite.jpeg",
    name: "Steel Grey Granite",
    category: "Granite",
    bestFor: "Floors, staircases, outdoor paving",
  },
  {
    id: 10,
    imgURL: "/products/white-carara.jpeg",
    name: "White Carrara",
    category: "Marble",
    bestFor: "Bathrooms, walls, luxury flooring",
  },
  {
    id: 11,
    imgURL: "/products/white-gold.jpeg",
    name: "White Gold",
    category: "Marble",
    bestFor: "Elegant living spaces, countertops",
  },
  {
    id: 12,
    imgURL: "/products/white-gold-galaxy.jpeg",
    name: "White Gold Galaxy",
    category: "Granite",
    bestFor: "Premium kitchens, statement surfaces",
  },
  // {
  //   id: 13,
  //   imgURL: "/products/black.jpeg",
  //   name: "Black Granite",
  //   category: "Granite",
  //   bestFor: "Modern kitchens, sleek interiors",
  // },
];